version: '3.8'

services:
  # 들어오는 모든 요청을 php 인터프린터로 트리거 합니다.
  server:
    # image: 'nginx:stable-alpine'
    build: 
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
  # php 코드와 laravel 코드를 실행합니다.
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  # 데이터베이스
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  # php 써드파티 패키지 매니저 -> laravel 애플리케이션 생성
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # laravel 자체 도구 (데이터베이스 마이그레이션 실행 등..)
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint:
      - php
      - /var/www/html/artisan
    env_file:
      - ./env/php.env
  # # js 코드 실행
  npm:
    image: 'node:l18'
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html